### PR TITLE
Drop repeated states

### PR DESCRIPTION
**Pull request by eskimor**
A litte optimzation, which makes it possible for users to only trigger state updates on actual state change and not on every action.

### CODE REVIEW

**Comment by eskimor** [comment]
Personally I get more and more convinced that the better solution would be to put a `Maybe State` in the EffModel instead of `State`. With `Nothing` meaning: State has not changed - this would be a more robust solution.

In any case - this PR is backwards compatible and enables users (me) to experiment with solutions like `Maybe State`, as it is easy to translate a `Maybe State` eff model to a `State` eff model with a foldp - which obviously is only useful with this PR.

**Comment by maddie927** [comment]
That seems like an excellent idea.  Much more explicit and barely more work (`update _ state = state` -> `update _ _ = Nothing`).

**Comment by eskimor** [comment]
Resolved merge conflict due to recent PR merges - should be fine now, but let's wait what travis says ;-)

**Comment by eskimor** [comment]
Ok - travis says it is fine now.

**Comment by sleexyz** [comment]
This should be performant since `dropRepeats` drops based on reference equality for objects.

**Comment by eskimor** [comment]
The downside is - the user has to be very careful with nested component updates if he wants to take advantage of this optimization.

**Comment by eskimor** [comment]
The Maybe solution sucks quite a bit in practice - but I found an even better solution already. Based on a state monad, with a convenient liftChild function, which takes care of smartly updating the parent's state. - It is not finished yet, because to make it really shine we need FunDeps and I haven't got the time yet to make everything work with the new psc-0.10.1.

You can have a look at my work [here](https://github.com/gonimo/gonimo-front/blob/master/src/Gonimo/Pux.purs). Put to use [here](https://github.com/gonimo/gonimo-front/blob/master/src/Gonimo/UI/Loaded.purs#L130) for example.

I have to say the "update state only on actual state change" problem is only one of the problems/inconveniences I had with pux, this approach solves - I am really happy with it.

**Comment by epsilonhalbe** [comment]
hey @alexmingoia will this branch be merged in the near future?

**Pull request merged**
