### PR TITLE
updates dependencies and code to be compatible with purs 0.12

### PR DESCRIPTION
**Pull request by roryc89**
Updates dependencies and code to be compatible with purs 0.12. #157 

I am relatively new to Purescript and totally new to Pux so sorry if there are mistakes. I'm especially not sure if the  `unsafePerformEffect` in `src/Pux/DOM/History.purs` is ok.

### CODE REVIEW

**Comment by maddie927** [comment]
Nice, looks really close at least! Updating the examples to see if the tests pass will probably answer your `unsafePerformEffect` question.

**Comment by roryc89** [comment]
Thanks @spicydonuts. Updating the examples now.

**Comment by roryc89** [comment]
Examples are building except for the react-interop example, which has a missing MissingFFIModule error `The foreign module implementation for module ReactInteropExample.ReactComponent is missing.`.

 I wasn't aware of purs 0.12 changes that would effect this behaviour so just  wanted to check that this was building successfully previously and that I wasn't missing a build step.

**Comment by alexmingoia** [comment]
Thank you for updating this.

**Pull request merged**
